---
title: John Bauters for Emeryville
description: Environmentalist, Democrat, local non-profit advocate fighting for housing and disadvantaged communities in the East Bay.
meta_img:
twitter:
favicon: /img/favicon-32x32.png
url: https://johnbauters.net
#baseurl: /john-bauters
gtm: GTM-W6NH8XF
schema:
  name: John Bauters
  type: Person
  image: /img/jb-headshot.png
  job-title: "Council Member"
  affiliation:
    type: Organization
    name: Emeryville City Council
  social:
  - https://twitter.com/JohnBauters
timezone: America/New York
future: true
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gruntfile.js
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
collections:
  pages:
    output: true  
  redirects: 
    output: true  
defaults:
- scope:
    path: ''
  values:
    layout: default
- scope:
    type: 'redirects'
  values: 
    layout: 'redirect'  
- scope: 
    type: 'posts'
  values: 
    layout: 'post'      