collections_config:
  posts:
    name: Posts
    path: _posts
    schemas:
      default:
        path: .cloudcannon/schemas/blog-post.md
        name: Blog post
        _enabled_editors:
          - content
        _inputs:
          $.title:
            comment: The title of your blog post
  redirects:
    name: Redirects
    path: _redirects
    add_options: []
  pages:
    name: Pages
    path: _pages
    add_options: []
    schemas:
      about:
        path: .cloudcannon/schemas/about.md
        name: About
        _enabled_editors:
          - data
          - content
        text_key: title
      endorsements:
        path: .cloudcannon/schemas/endorsements.md
        name: Endorsements
        _enabled_editors:
          - data
        _inputs:
          $.org-endorsements.list:
            type: array
            options:
              structures: _structures.endorsements-list
          $.leader-endorsements.disclaimer: 
            type: markdown     
      issues:
        path: .cloudcannon/schemas/issues.md
        name: Issues
        _enabled_editors:
          - data
        _inputs:
          $.issue-summary.image.src:
            type: file
          $.issues:
            type: array
            options:
              structures: _structures.issues-issues
      home:
        path: .cloudcannon/schemas/home.md
        name: Home
        _enabled_editors:
          - data
        _inputs:
          $.issues.items:
            type: array
            options:
              structures: _structures.home-items
collection_groups:
  - heading: Content
    collections:
      - posts
      - redirects
      - pages
paths:
  static: ''
  uploads: img
_structures:
  endorsements-list:
    values:
      - value:
          title: ''
          logo: null
        _inputs:
          logo:
            type: image
  home-items:
    values:
      - value:
          title: ''
          image: null
          link: ''
  issues-issues:
    values:
      - value:
          title: ''
          id: ''
          subtitle: ''
          text: ''
        _inputs:
          text:
            type: markdown
_inputs:
  template:
    hidden: true
  css: 
    hidden: true  
  permalink: 
    hidden: true    
  intro.text:
    type: markdown