collections_config:
  posts:
    name: Posts
    path: _posts
    schemas:
      default:
        path: .cloudcannon/schemas/blog-post.md
        name: Blog post
        _enabled_editors:
          - content
        _inputs:
          $.title:
            comment: The title of your blog post
          $.date: 
             type: datetime
          $.published: 
            comment: Switch on to show the post, off to hide it from the news feed.
            type: switch  
  redirects:
    name: Redirects
    path: _redirects
collection_groups:
  - heading: Content
    collections:
      - posts
      - redirects
      - pages
  - heading: Settings
    collections: 
    - data     
paths:
  static: ''
  uploads: img
  data: _data
_structures:
  endorsements-list:
    values:
      - value:
          title: ''
          logo: null
        _inputs:
          logo:
            type: image
  home-items:
    values:
      - value:
          title: ''
          image: null
          link: ''
_inputs:
  template:
    hidden: true
  css: 
    hidden: true  
  permalink: 
    hidden: true    
  intro.text:
    type: markdown
  layout: 
    hidden: true  

data_config: 
  nav-menu: true  

